model_list:
  - model_name: antigravity-router
    litellm_params:
      model: gemini/gemini-3.1-flash-lite
#   - model_name: antigravity-fallback-1
#     litellm_params:
#       model: gemini/gemini-2.5-flash-lite
#   - model_name: antigravity-fallback-2
#     litellm_params:
#       model: gemini/gemini-3.5-flash
#   - model_name: antigravity-fallback-3
#     litellm_params:
#       model: gemini/gemini-3-flash
#   - model_name: antigravity-fallback-4
#     litellm_params:
#       model: gemini/gemini-2.5-flash
  - model_name: text-embedding-3-small
    litellm_params:
      model: gemini/gemini-embedding-2
      rpm: 90

